package dev.railroadide.railroad.ide.sst.lexer;

/** Additional token properties independent of the language-specific token kind. */
public enum TokenFlag {
    /** Marks the end of the input. */
    EOF, // Indicates that the token is the end of the file or input stream.
    /** Marks a lexical error such as an invalid character or malformed token. */
    ERROR, // Indicates that the token is an error, such as an invalid character or malformed token.
    /** Marks an incomplete token such as an unterminated literal or comment. */
    INCOMPLETE, // Indicates that the token is incomplete, such as an unterminated string or comment.
    /** Marks a generated token that is not present in the source text. */
    SYNTHETIC // Used for tokens that are generated by the lexer but not present in the source code.
}
