package dev.railroadide.railroad.ide.sst.lexer;

public enum TokenFlag {
    EOF, // Indicates that the token is the end of the file or input stream.
    ERROR, // Indicates that the token is an error, such as an invalid character or malformed token.
    INCOMPLETE, // Indicates that the token is incomplete, such as an unterminated string or comment.
    SYNTHETIC // Used for tokens that are generated by the lexer but not present in the source code.
}
