package io.github.railroad.PluginManager;

public enum PluginStates {
    NOTLOADED, STARTING_INIT, ERROR_INIT, FINSIHED_INIT, LOADING, LOADED, ACTIVITY_UPDATE_START, ACTIVITY_UPDATE_FINSIHED, ACTIVITY_UPDATE_ERROR
}
