name: JavaFX CI/CD Pipeline

# When to run: on push to main branch and pull requests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: self-hosted
    
    steps:
    # Get your code
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Install Java 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    # Cache Gradle dependencies (speeds up builds)
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    # Make gradle wrapper executable
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    # Run tests
    - name: Run tests
      run: ./gradlew test
    
    # Create JavaFX distribution packages
    - name: Create JavaFX packages
      run: ./gradlew jpackageInstaller
    
    # Upload build artifacts (so you can download them)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: railroad-${{ github.sha }}
        path: |
          build/distributions/
          build/jpackage/
        retention-days: 30
