name: test.yml
on:
  push:

jobs:
  curl:
    runs-on: ubuntu-latest

    steps:
      - name: Curl package pom
        run: |
          curl https://maven.railroadide.dev/releases/dev/railroadide/RailroadLogger/1.0.1/RailroadLogger-1.0.1.pom
